### ISSUE TITLE
When trying to push on GitHub, username is not recognised

### ISSUE THREAD

**Issue by tevgeniou** [InseadDataAnalytics/INSEADAnalytics#3]

**Comment by jekinpatel** [comment]
Hi Theo,

I am an Alum, I might be getting these emails by mistake, thanks.

Jekin Patel
Sent from my iPhone

On Sep 10, 2015, at 10:56 AM, Theos Evgeniou <notifications@github.com<mailto:notifications@github.com>> wrote:


-

**Comment by tevgeniou** [comment]
Hi Jekin,

Good to hear from you. Hope all is good!

Sorry you get this: you will need to "unwatch" the github project to stop these at https://github.com/InseadDataAnalytics/INSEADAnalytics .  Started teaching the course again just today.

Well, good excuse to get in touch. Stay more in touch! Where are you these days?

Cheers,
Theos

**Comment by Sefimenko** [comment]
Professor, I had this problem and I solved it with this guide. I see my "first R script" on git hub. But now I tried to create "second R script" and when I committed it I got his error message:

fatal: Unable to create '/Users/sergeyefimenko/Desktop/R/introtoBDA/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

and my Rstudio looks like this:
![screen shot 2016-01-08 at 12 47 55](https://cloud.githubusercontent.com/assets/16547104/12195147/3113a1c6-b606-11e5-8e36-4ea9dc9ef3b5.png)

My Github looks like this:
![screen shot 2016-01-08 at 12 51 06](https://cloud.githubusercontent.com/assets/16547104/12195208/9734e564-b606-11e5-8a7c-8a56acab79b9.png)

How can I solve that issue? How can I remove the file manually to continue?

Thanks, 
Sergey Efimenko

**Comment by Sefimenko** [comment]
I have the following problem. First, I created "my third script".
![screen shot 2016-01-08 at 21 51 39](https://cloud.githubusercontent.com/assets/16547104/12206524/80ff6584-b652-11e5-92d2-ec677dc63780.png)

Then I clicked "Commit" and got this:
![screen shot 2016-01-08 at 21 52 08](https://cloud.githubusercontent.com/assets/16547104/12206545/9aa2f852-b652-11e5-9f8c-4ddff6fed44e.png)

Then, have written a message in commit message menu, clicked Comit and got this message:
![screen shot 2016-01-08 at 21 52 24](https://cloud.githubusercontent.com/assets/16547104/12206603/e53ccc94-b652-11e5-82a8-34eedcb0c2bc.png)

After that I decided to push this script, clicked push button and got this:
![screen shot 2016-01-08 at 21 52 48](https://cloud.githubusercontent.com/assets/16547104/12206620/0392fb8c-b653-11e5-8731-5643d28f644a.png)

So it seems to me that something works wrong (at least not as in Video 5). the message after I pressed commit was strange. So my question is how can I make this process of committing and pushing as it should be?

Thanks!

**Comment by tevgeniou** [comment]
maybe check this http://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists 

also, try to learn the git commands from a command line. To do that go to "Tools -> Shell"

![screen shot 2016-01-09 at 18 05 45](https://cloud.githubusercontent.com/assets/1362763/12217258/bcf1e284-b6fb-11e5-9098-991c372289d1.png)

then just time git and you will see all commands. sometimes it is better to do the git work via the shell. 

![screen shot 2016-01-09 at 18 06 02](https://cloud.githubusercontent.com/assets/1362763/12217261/c636537a-b6fb-11e5-906b-369d85dd2daa.png)

**Comment by tevgeniou** [comment]
here are some examples
https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html

**Comment by tevgeniou** [comment]
for example something like this should solve the problem (through Shell commands
![screen shot 2016-01-09 at 22 29 41](https://cloud.githubusercontent.com/assets/1362763/12218519/ef5e6ea6-b721-11e5-91d5-a1432ed8953c.png)

**Comment by Sefimenko** [comment]
I tried to put several proposed here http://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists  commands into shell and still don't have the error messages when commit. Thanks!

**Comment by riyachhabra** [comment]
This helped me fix the username problem on Mac - http://stackoverflow.com/questions/6565357/git-push-requires-username-and-password
